before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: waitup
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE

nfpms:
  - maintainer: Will Chellman <creaked@gmail.com>
    description: A tool to monitor system availability via RDP or SSH
    homepage: https://github.com/creaked/waitup
    license: MIT
    formats:
      - deb
      - rpm

brews:
  - name: waitup
    homepage: "https://github.com/creaked/waitup"
    description: "A tool to monitor system availability via RDP or SSH"
    repository:
      owner: creaked
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Will Chellman
      email: creaked@gmail.com

msi:
  - name: waitup
    short_description: "System availability monitor"
    long_description: "A tool to monitor system availability via RDP or SSH"
    product_name: Waitup
    publisher: Will Chellman
    homepage: "https://github.com/creaked/waitup"
    license: MIT
    env:
      - CGO_ENABLED=0
    wix:
      upgrade_code: "4552d2d3-259e-4fc6-9f57-a83f68f0b80e"
      product_code: "4552d2d3-259e-4fc6-9f57-a83f68f0b80f"
      add_to_path: true
      license: LICENSE

checksum:
  name_template: "checksums.txt"
