before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: waitup
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

nfpms:
  - maintainer: Will Chellman <creaked@gmail.com>
    description: A tool to monitor system availability via RDP or SSH
    homepage: https://github.com/creaked/waitup
    license: MIT
    formats:
      - deb
      - rpm

brews:
  - name: waitup
    homepage: "https://github.com/creaked/waitup"
    description: "A tool to monitor system availability via RDP or SSH"
    repository:
      owner: creaked
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Will Chellman
      email: creaked@gmail.com

aurs:
  - name: waitup-bin
    homepage: https://github.com/creaked/waitup
    description: A utility to check when a system/service becomes available (RDP/SSH/Port)
    maintainers:
      - 'Will Chellman <creaked at gmail dot com>'
      - 'Jonathan Neidel <aur at jneidel dot com>'
    license: MIT
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/waitup-bin.git'
    package: |-
      # bin
      install -Dm755 "./waitup" "${pkgdir}/usr/bin/waitup"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

checksum:
  name_template: 'checksums.txt' 
