before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: waitup
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

nfpms:
  - maintainer: Will Chellman <creaked@gmail.com>
    description: A tool to monitor system availability via RDP or SSH
    homepage: https://github.com/creaked/waitup
    license: MIT
    formats:
      - deb
      - rpm

chocolateys:
  - name: waitup
    title: Waitup
    authors: Will Chellman
    project_url: https://github.com/creaked/waitup
    license_url: https://github.com/creaked/waitup/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/creaked/waitup
    docs_url: https://github.com/creaked/waitup
    bug_tracker_url: https://github.com/creaked/waitup/issues
    tags: "rdp ssh monitor utility cli"
    summary: A tool to monitor system availability via RDP or SSH
    description: |
      Waitup is a command-line utility that monitors systems for RDP or SSH availability.
      Perfect for checking when a system becomes available after reboot.
    release_notes: "https://github.com/creaked/waitup/releases/tag/v{{ .Version }}"

brews:
  - name: waitup
    homepage: "https://github.com/creaked/waitup"
    description: "A tool to monitor system availability via RDP or SSH"
    repository:
      owner: creaked
      name: homebrew-tap
    commit_author:
      name: Will Chellman
      email: creaked@gmail.com

checksum:
  name_template: 'checksums.txt' 